name: AutoMerge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  Dependabot_Automerge:
    uses: intel-innersource/frameworks.actions.dependabot-automerge/.github/workflows/dependabot_automerge_pr.yml@main
    with:
      DEPENDABOT_RUNNERS: "['ubuntu-latest']"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
