name: Coverity

on:
  workflow_dispatch:
 
permissions: read-all
 
jobs:
  coverity:
    name: Coverity
    runs-on: ubuntu-22.04
    env:
      COV_TOKEN: jQxsG_hSGU57M7A7lqyBvg
 
    defaults:
      run:
        shell: bash -leo pipefail {0}
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Cache coverity
        id: cache-coverity
        uses: actions/cache@v4
        env:
          COVERITY_CACHE_NUMBER: 1  # Increase to reset cache
        with:
          path: |
            /home/runner/coverity
          key: ${{ runner.os }}-${{ env.COVERITY_CACHE_NUMBER }}
 
      - name: Download coverity
        if: steps.cache-coverity.outputs.cache-hit != 'true'
        run: |
          cd
          curl -X POST https://scan.coverity.com/download/linux64 -d "token=$COV_TOKEN" --data-urlencode "project=MLIR Extensions" -o coverity.tgz
          tar zxf coverity.tgz
          mv -T cov-analysis-linux64-* coverity
 
      - name: Add coverity to PATH
        run: |
          echo "$HOME/coverity/bin" >> $GITHUB_PATH
 
      - name: Show coverity version
        run: |
          coverity --version
